In [5]:
import torch
import random
t = torch.arange(50).reshape((5,10))
a = torch.tensor([1,2,1,1,1]).reshape((5,1))
print(t.shape)
print(a.shape)
print(t)
print(a)
torch.gather(t, 1, a)

torch.Size([5, 10])
torch.Size([5, 1])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])
tensor([[1],
        [2],
        [1],
        [1],
        [1]])


tensor([[ 1],
        [12],
        [21],
        [31],
        [41]])